# Generated by Django 5.2.5 on 2025-08-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
